# Generated by Django 5.1.6 on 2025-02-06 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('aberto', 'Em Aberto'), ('aguardando', 'Aguardando'), ('andamento', 'Em Andamento'), ('sem_resolucao', 'Sem Resolução'), ('resolvido', 'Resolvido')], default='aberto', max_length=20)),
                ('usuario_acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_executadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_afetado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_afetadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
